### ISSUE TITLE
Can I use the checkpoints provided on other templates?

### ISSUE THREAD

**Issue by nuuuh** [agiresearch/InstructGLM#1]
Hi, I got similar result on Arxiv dataset by using the code and checkpoint you provided, but I also found you are using structure-free setting during testing. When I change the template from '6-6-6-7' to '2-3-3-2', there's a large decrease in acc (Giant: 76.20%->69.91%; OGB: 75.65%->44.90%). I'm directly using the checkpoint provided and I wonder if this is normal? Thank you.

**Comment by RuosongYe** [comment]
Hi, thank you for your interests in our work. The reported results on ogbn-arxiv in our paper is the test accuracy for prompt 6-6-6-7 (structure-free template). The pipeline of the project includes three phases: model traning, model validation, and model testing. Specifically, during the validation phase, we tested all templates and selected the optimal one based on validation results then conduct inference on the test set (i.e., 6-6-6-7 for ogbn-arxiv). During the validation phase we also observed that high-order templates like 2-3-3-2 doesn't produce excellent results, that is why we didn't select this prompt for final testing. However, we found that incorporating high-order prompts during training helps the model learn long-distance structural information better and ultimately leads to improved best performance on the optimal prompt selected via validation. In addition to 6-6-6-7, we noticed that 2-3-1-2 also usually performs well if you want to apply the checkpoint to another tempalte with graph structure. Furthermore, if your GPU memory allows, we recommend increasing the maximum length limit of input sentences during inference, as this can contribute to even better results. For more training details, please refer to the note.txt we provided.

**Comment by nuuuh** [comment]
I'll try 2-3-1-2. Thanks a lot for your help!

**Comment by xbxiong** [comment]
I had some problems running the sample script with reference to the environment configuration in the repo. It seems that you have successfully run it. Could you please provide some information about your environment configuration? Thanks

**Comment by nuuuh** [comment]
> I had some problems running the sample script with reference to the environment configuration in the repo. It seems that you have successfully run it. Could you please provide some information about your environment configuration? Thanks

Hi, I remember there was a package conflict and I fixed that by switching to a different version of tokenizer. I read the log you provided in your issue and I think you should try using tokenizer==0.13.3 instead of tokenizer==0.14.0.

**Comment by xbxiong** [comment]
> > I had some problems running the sample script with reference to the environment configuration in the repo. It seems that you have successfully run it. Could you please provide some information about your environment configuration? Thanks
> 
> Hi, I remember there was a package conflict and I fixed that by switching to a different version of tokenizers. I read the log you provided in your issue and I think you should try using tokenizers==0.13.3 instead of tokenizers==0.14.0.

Thanks. I've already done that
