### ISSUE TITLE
[E ProcessGroupNCCL.cpp:821] [Rank 1] Watchdog caught collective operation timeout: 

### ISSUE THREAD

**Issue by xbxiong** [agiresearch/InstructGLM#3]
I meet another question when i run the script
```
Watchdog caught collective operation timeout: WorkNCCL(SeqNum=49, OpType=ALLREDUCE, Timeout(ms)=18000000) ran for 18005607 milliseconds before timing out.
```
This seems to be a time-out problem, but I have tried the following by searching for related problems, but it still not work
```
dist.init_process_group(backend='nccl',timeout=timedelta(seconds=18000)) # (i tried 5 hours it still not work)

export NCCL_DEBUG=info
export NCCL_IB_GID_INDEX=3
export NCCL_IB_HCA=mlx5_2:1
export NCCL_IB_SL=3
export NCCL_CHECKS_DISABLE=1
export NCCL_LL_THRESHOLD=16384
export NCCL_IB_CUDA_SUPPORT=1
export NCCL_IB_DISABLE=1
export NCCL_P2P_DISABLE=1
export NCCL_SOCKET_IFNAME=eth1
export NCCL_P2P_LEVEL=NVL
```
I want to know how you configure it

**Comment by RuosongYe** [comment]
May I ask if the training process has started normally? If so, what percentage has the training progress bar reached?

**Comment by xbxiong** [comment]
![bug1](https://github.com/agiresearch/InstructGLM/assets/61233162/88c85d12-8ce8-4dbf-9257-ee186fa3d44d)

Looks like it just started ，But it's stuck in the beginning (0%)

**Comment by DITINGmisa** [comment]
Hello, xbxiong. I have encountered the same problem, how did you solve the problem of  jamming?
