### ISSUE TITLE
Question with the cora preprocess

### ISSUE THREAD

**Issue by Tsukumo1** [agiresearch/InstructGLM#4]
Hi I have some questions about the code in the data preprocessing part of cora. What are 'tape_cora.pkl' and 'cora_tape.pkl'? I noticed that you seem to use it directly in your code.

**Comment by Tsukumo1** [comment]
Hi I have some questions about the code in the data preprocessing part of cora. What is 'tape_cora.pkl'? I noticed that you seem to use it directly in your code.

**Comment by RuosongYe** [comment]
Hi, thanks for the interests in our work. We have updated the data_preprocess scripts by adding detailed notes. Also please feel free to directly download the preprocessed data via our provided links.
