### ISSUE TITLE
size mismatch for trans_1.weight: copying a param with shape torch.Size([512, 768]) from checkpoint, the shape in current model is torch.Size([512, 1433]).

### ISSUE THREAD

**Issue by NEU20205988John** [agiresearch/InstructGLM#5]
size mismatch for trans_1.weight: copying a param with shape torch.Size([512, 768]) from checkpoint, the shape in current model is torch.Size([512, 1433]).
I was trying to do inference with the checkpoint provided, but found size mismatch. Is the checkpoint only for Arxiv dataset? If I wish to do inference on Cora or PubMed, do I have to train them first or I can do changes to directly do inference?

/opt/conda/envs/InstructGLM/lib/python3.8/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
Configurations
{'adam_beta1': 0.9,
 'adam_beta2': 0.999,
 'adam_eps': 1e-08,
 'backbone': './7B',
 'batch_size': 4,
 'clip_grad_norm': 1.0,
 'comment': '',
 'distributed': True,
 'do_lower_case': False,
 'dropout': 0.1,
 'dry': False,
 'epoch': 2,
 'fp16': False,
 'from_scratch': False,
 'gen_max_length': 64,
 'gradient_accumulation_steps': 8,
 'inference': True,
 'load': None,
 'local_rank': 0,
 'log_train_accuracy': False,
 'losses': 'classification',
 'lr': 8e-05,
 'max_text_length': 512,
 'multiGPU': True,
 'num_beams': 1,
 'num_workers': 8,
 'optim': 'adamw',
 'optimizer': 'adamw',
 'output': 'snap/cora-7b',
 'seed': 42,
 'submit': False,
 'test': None,
 'test_only': False,
 'tokenizer': 'LlamaTokenizerFast',
 'train': 'Cora',
 'valid': 'Cora',
 'valid_batch_size': None,
 'warmup_ratio': 0.05,
 'weight_decay': 0.0}
['classification_loss']
Process Launching at GPU 0
Building val loader at GPU 0
Data sources:  ['Cora']
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 144631.17it/s]
compute_datum_info
Length of test dataset: 6504
Building Model at GPU 0
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:24<00:00, 12.45s/it]

trainable params: 17354752 || all params: 6755770368 || trainable%: 0.25688783150777456

NCCL version 2.14.3+cuda11.7
Model Launching at GPU 0
It took 0.0s
Traceback (most recent call last):
  File "llama_cora_src/pretrain.py", line 774, in <module>
    main_worker(args.local_rank, args)
  File "llama_cora_src/pretrain.py", line 730, in main_worker
    trainer.test()
  File "llama_cora_src/pretrain.py", line 564, in test
    self.load_checkpoint(ckpt_path)
  File "/root/paddlejob/workspace/env_run/jiangwenyuan/GraphPrompt_code/InstructGLM/llama_cora_src/trainer_base.py", line 139, in load_checkpoint
    results = self.first_model.load_state_dict(state_dict, strict=True)   
  File "/opt/conda/envs/InstructGLM/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for FP:
        size mismatch for trans_1.weight: copying a param with shape torch.Size([512, 768]) from checkpoint, the shape in current model is torch.Size([512, 1433]).
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 156625) of binary: /opt/conda/envs/InstructGLM/bin/python
Traceback (most recent call last):
  File "/opt/conda/envs/InstructGLM/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/InstructGLM/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/InstructGLM/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/opt/conda/envs/InstructGLM/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/opt/conda/envs/InstructGLM/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/opt/conda/envs/InstructGLM/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/opt/conda/envs/InstructGLM/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/envs/InstructGLM/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
llama_cora_src/pretrain.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-01-29_16:34:37
  host      : 10-67-250-143.job-0bb658bd58971c9b-trainer-0.4fc90aaa-4cc6-525c-8ba1-4a9f8b0e532b.svc.cluster.local
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 156625)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by pujacomputes** [comment]
Hi! I'm running into the same error trying to use the provided checkpoints for inference. Do you mind sharing how you fixed it? Thank you!
