### ISSUE TITLE
Get stuck training the Arxiv dataset

### ISSUE THREAD

**Issue by xbxiong** [agiresearch/InstructGLM#6]
We successfully run the cora and pubmed datasets, but after running the training script（llama） for arxiv, the program becomes get struck. By printing some information, we find that loss appears with **nan** value after the first iteration，We think this may be the cause of problem. 

Have you encountered the same problem?

- Device : 4 * A800(80 g)
- Environment configuration:
We install the environment strictly according to the library version provided in the repo，And we tried using a later version of the transform library and still had this problem

![image](https://github.com/agiresearch/InstructGLM/assets/61233162/d75f04c8-c3f7-495a-90ab-fcd11f51a923)

**Comment by RuosongYe** [comment]
I didn't meet such a problem before. However, I can rerun and help see if anything unusual.

**Comment by initzhang** [comment]
Hi @RuosongYe @xbxiong , I encountered the same problem here with A800*2 on the arXiv dataset. Do you have any solutions for this?

**Comment by agiresearch** [comment]
Closed since unable to reproduce the issue.
