### ISSUE TITLE
missing prompt explanations like 2-3-1-2

### ISSUE THREAD

**Issue by initzhang** [agiresearch/InstructGLM#7]
Hello team, thanks for this inspiring work! 

I find that some prompts are not explained in the paper, such as `2-3-1-2`, `2-3-2-4` and `6-6-6-7` as shown in the [line of code here](https://github.com/agiresearch/InstructGLM/blob/dd2dd5ecc48089a44402a4e0744abf891be0c3c8/llama_pubmed_src/pretrain.py#L687). It seems that the numbering rules here are not consistent with the Appendix.D of [the paper](https://arxiv.org/pdf/2308.07134.pdf). Could you tell me what is the correct prompt rule for the code? Thank you!

**Comment by RuosongYe** [comment]
Please feel free to check the all_graph_templates.py python file, which are all aligned. Thank you.
